package controllers

import (
	"net/http"
	"time"

	"github.com/GenkiNakashima/moneyst/backend/config"
	"github.com/GenkiNakashima/moneyst/backend/middleware"
	"github.com/GenkiNakashima/moneyst/backend/models"
	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
)

func CreateSimulationTrade(c *gin.Context) {
	userID, err := middleware.GetUserID(c)
	if err != nil {
		c.JSON(http.StatusUnauthorized, gin.H{"error": "Unauthorized"})
		return
	}

	var req models.TradeRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	trade := models.SimulationTrade{
		UserID:     userID,
		Symbol:     req.Symbol,
		TradeType:  req.TradeType,
		EntryPrice: req.EntryPrice,
		Quantity:   req.Quantity,
		EntryAt:    time.Now(),
	}

	if err := config.DB.Create(&trade).Error; err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to create trade"})
		return
	}

	c.JSON(http.StatusCreated, trade)
}

func GetSimulationTrades(c *gin.Context) {
	userID, err := middleware.GetUserID(c)
	if err != nil {
		c.JSON(http.StatusUnauthorized, gin.H{"error": "Unauthorized"})
		return
	}

	var trades []models.SimulationTrade
	if err := config.DB.Where("user_id = ?", userID).Order("entry_at DESC").Find(&trades).Error; err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to fetch trades"})
		return
	}

	c.JSON(http.StatusOK, trades)
}

func CloseSimulationTrade(c *gin.Context) {
	userID, err := middleware.GetUserID(c)
	if err != nil {
		c.JSON(http.StatusUnauthorized, gin.H{"error": "Unauthorized"})
		return
	}

	tradeID := c.Param("id")
	var req models.CloseTradeRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	var trade models.SimulationTrade
	if err := config.DB.Where("id = ? AND user_id = ?", tradeID, userID).First(&trade).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "Trade not found"})
		return
	}

	if trade.ExitPrice != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Trade already closed"})
		return
	}

	now := time.Now()
	trade.ExitPrice = &req.ExitPrice
	trade.ExitAt = &now

	// Calculate profit/loss
	var profitLoss float64
	if trade.TradeType == "buy" {
		profitLoss = (req.ExitPrice - trade.EntryPrice) * trade.Quantity
	} else {
		profitLoss = (trade.EntryPrice - req.ExitPrice) * trade.Quantity
	}
	trade.ProfitLoss = &profitLoss

	if err := config.DB.Save(&trade).Error; err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to close trade"})
		return
	}

	c.JSON(http.StatusOK, trade)
}

func GetTradeDiaries(c *gin.Context) {
	userID, err := middleware.GetUserID(c)
	if err != nil {
		c.JSON(http.StatusUnauthorized, gin.H{"error": "Unauthorized"})
		return
	}

	var diaries []models.TradeDiary
	if err := config.DB.Where("user_id = ?", userID).Order("diary_date DESC").Find(&diaries).Error; err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to fetch diaries"})
		return
	}

	c.JSON(http.StatusOK, diaries)
}

func UpdateTradeDiaryMemo(c *gin.Context) {
	userID, err := middleware.GetUserID(c)
	if err != nil {
		c.JSON(http.StatusUnauthorized, gin.H{"error": "Unauthorized"})
		return
	}

	diaryID := c.Param("id")
	var req struct {
		UserMemo string `json:"user_memo"`
	}
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	var diary models.TradeDiary
	if err := config.DB.Where("id = ? AND user_id = ?", diaryID, userID).First(&diary).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "Diary not found"})
		return
	}

	diary.UserMemo = req.UserMemo
	if err := config.DB.Save(&diary).Error; err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to update diary"})
		return
	}

	c.JSON(http.StatusOK, diary)
}

func GenerateTradeDiary(c *gin.Context) {
	userID, err := middleware.GetUserID(c)
	if err != nil {
		c.JSON(http.StatusUnauthorized, gin.H{"error": "Unauthorized"})
		return
	}

	tradeIDStr := c.Param("id")
	tradeID, err := uuid.Parse(tradeIDStr)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid trade ID"})
		return
	}

	var trade models.SimulationTrade
	if err := config.DB.Where("id = ? AND user_id = ?", tradeID, userID).First(&trade).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "Trade not found"})
		return
	}

	// TODO: Integrate with AI service for analysis
	// For now, generate a simple analysis
	analysis := "This is a placeholder for AI-generated analysis. In production, this would call an AI service."
	marketContext := "Market context would be generated by AI based on news and market data."

	diary := models.TradeDiary{
		UserID:            userID,
		TradeID:           &tradeID,
		GeneratedAnalysis: analysis,
		MarketContext:     marketContext,
		DiaryDate:         time.Now(),
	}

	if err := config.DB.Create(&diary).Error; err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to create diary"})
		return
	}

	c.JSON(http.StatusCreated, diary)
}
